### ISSUE TITLE
Feature Request: Options to Inspect Solution Accuracy

### ISSUE THREAD

**Issue by azev77** [RJDennis/SolveDSGE.jl#10]
Hi, 
I might have missed it but are there options to inspect the accuracy of a solution?
One common approach is to examine/plot residuals: for example ([here](https://sites.google.com/site/orenlevintal/taylor-projection))

**Comment by RJDennis** [comment]
I have given a bit of thought to doing this, but I haven't implemented anything yet.  It is something that should be included at some later stage, when I get more time to work on it.
