### ISSUE TITLE
Blanchard_kahn_form not defined 

### ISSUE THREAD

**Issue by jerryhxg** [RJDennis/SolveDSGE.jl#2]
where i can find "Blanchard_kahn_form" ?    when i ran, the code show it is not defined.  thank you for your kind help.

**Comment by RJDennis** [comment]
Blanchard_Kahn_Form (note the capitals) is defined inside types.jl.  I just ran linear_example from the examples folder, which uses Blanchard_Kahn_Form, and didn't encounter any problems.

**Comment by jerryhxg** [comment]
thanks a lot for your kind reply, Dennis. i also using linear_example.  but still run line 52 

m_bk = Blanchard_Kahn_Form(nx,ny,a,c,sigma),  it shows error "Blanchard_Kahn_Form  not defined".  dont know why, do i need any other setup besides  Pkg.add("SolveDSGE") and using SolveDSGE
?

**Comment by RJDennis** [comment]
After Pkg.add("SolveDSGE") run Pkg.checkout("SolveDSGE") to get the latest version from master.
