### ISSUE TITLE
Example with Finite Horizon

### ISSUE THREAD

**Issue by azev77** [RJDennis/SolveDSGE.jl#37]
Hi. 
I'm writing a [post](https://github.com/pulsipher/InfiniteOpt.jl/issues/131#issuecomment-867085644) on solving dynamic economic models in the Julia ecosystem. 
I'm interested in 4 broad categories of models: 
![image](https://user-images.githubusercontent.com/7883904/122686946-d5381000-d1e1-11eb-9cdd-1ef242559d14.png)
I have multiple solutions for the deterministic models. 
![image](https://user-images.githubusercontent.com/7883904/122806040-d88dd300-d297-11eb-8554-3d843ebd66f0.png)

Is it possible to use your package to solve finite horizon models?

**Comment by RJDennis** [comment]
The package is written with discrete-time infinite-horizon models in model and I haven't tried to extend it to finite-horizon problems (discrete-time, continuous-time, deterministic, or stochastic) as the solution techniqies used are often very different.

**Comment by azev77** [comment]
I'll leave this link here in case the issue comes up again: 
https://www.sciencedirect.com/science/article/pii/S0165188999000081
