### ISSUE TITLE
ERROR: LoadError: StackOverflowError:

### ISSUE THREAD

**Issue by salinasdcs** [RJDennis/SolveDSGE.jl#50]
Hi,

I was trying to execute the examples in my computer, but I got this error:

The model's variables are now in this order: ["z", "k", "c", "muc"]
ERROR: LoadError: StackOverflowError:
in expression starting at /Users/Github/SolveDSGE.jl/examples/example_one/solution_file_1a.jl:45

Something similar happens for the rest of examples, and I am not sure how to solve it. 

Any help is appreciated.

**Comment by RJDennis** [comment]
Hi ,

can you try running the simple example in the following link?

https://discourse.julialang.org/t/vs-code-stackoverflowerror/72704

I get the error when I run it in VS Code, but not when I run it directly in the Julia REPL (outside VS Code).

Anyway, this is the source of the problem, which is causing errors for the Smolyak solution.

Richard

**Comment by salinasdcs** [comment]
Hi,

Thanks for the quick reply. Running the examples directly in the Julia REPL works for me. 

Cesar
