### ISSUE TITLE
ChebyshevSchemeStoch

### ISSUE THREAD

**Issue by pbrazval** [RJDennis/SolveDSGE.jl#77]
Hi there,
when I run example "solution_file_stoch_growth_mod.jl" in the folder, the compiler cannot match the arguments of ChebyshevSchemeStoch, yielding the error

```
ERROR: MethodError: no method matching ChebyshevSchemeStoch(::Vector{Float64}, ::typeof(chebyshev_nodes), ::Vector{Int64}, ::Int64, ::Vector{Int64}, ::Matrix{Float64}, ::Float64, ::Float64, ::Int64, ::Symbol)

Closest candidates are:
  ChebyshevSchemeStoch(::Union{Vector{T}, T}, ::Function, ::Union{Vector{S}, S}, ::S, ::Union{Vector{S}, S}, ::VecOrMat{T}, ::T, ::T, ::S) where {T<:Real, S<:Integer}
   @ SolveDSGE ~/.julia/packages/SolveDSGE/C7sTY/src/structures.jl:106
```

when I call

```
C   = ChebyshevSchemeStoch(ss,chebyshev_nodes,[21,21],9,[5,5],[0.15 27.0; -0.15 17.0],tol,1e-6,maxiters,:newton)
```

Can anyone help me?
Thanks,
Pedro

**Comment by RJDennis** [comment]
Hi Pedro,

can you first make sure that you are using the most recent version of SolveDSGE.jl and let me know if the problem persists.

Richard

**Comment by RJDennis** [comment]
Hi Pedro,

if your problem has been resolved, then can you please close this issue.

Richard

**Comment by pbrazval** [comment]
Hi Richard,
thank you for answering my query. Somehow I had imported an old version of SolveDSGE -- with v0.5.6 this error does not appear anymore.
Closing the issue.
Best
Pedro
