### ISSUE TITLE
Declaration order of variables and equations

### ISSUE THREAD

**Issue by rmauad** [RJDennis/SolveDSGE.jl#78]
Dear Professor Dennis,
 
I work at the Research Department of the Central Bank of Brazil, and our team has been using the SolveDSGE package for Julia. I am contacting you to confirm some findings about the package.
 
Using the attached example model (“test_kf.txt”), we found that the declaration of variables, shocks, and equations must follow a specific pattern to ensure the order of the coefficients in the solution matrices H and K are consistent. In the attached file “Declaration order of variables and equations.docx”, I describe this pattern which depends on the endogenous or exogenous nature of the variables. In the example model, we have two exogenous variables me_X and Y, and one endogenous: XX – which depends on Y.

By breaking each of the steps described in this file, the order of the coefficients in the solution matrix H becomes inconsistent with those in matrix K. Please see the attached “Solution matrices.docx” file.
 
Could you please confirm if our understanding is correct? If so, may I suggest that you include a “declaration order” section in the package manual?
 
Thank you in advance.
Best regards,
Roberto Baltieri Mauad 
[Declaration order of variables and equations.docx]
(https://github.com/RJDennis/SolveDSGE.jl/files/13599985/Declaration.order.of.variables.and.equations.docx)
[Solution matrices.docx](https://github.com/RJDennis/SolveDSGE.jl/files/13599990/Solution.matrices.docx)
[Archive.zip](https://github.com/RJDennis/SolveDSGE.jl/files/13599995/Archive.zip)

**Comment by RJDennis** [comment]
Hi Roberto,

I have received and read your comment, but I haven't had time to look into it.  I believe I know what you are referring to, however, but I'll wait until I have a chance to look into it before I respond.

Richard

**Comment by rmauad** [comment]
No problem, please take your time. Thank you!

**Comment by paulbousquet** [comment]
I just encountered a similar issue -- an error was thrown that the shocks weren't AR(1). When I printed the relevant line of code in solution_functions.jl, the matrix being checked to be a diagonal was [0 1;1 0]. My shocks were listed as e_r, e_a in the shocks block, but in the equations block the equation for A (containing e_a) was entered first. Once I switched them, this was no longer a problem.

**Comment by RJDennis** [comment]
Paul,

I have been looking into the issue you raise.  Are you able to send me a short model.txt file that illustrates the problem you are having?  You are welcome to send it to me by email if you don't want to post it here.

**Comment by paulbousquet** [comment]
Richard, 

Here is the file. Note that if I change the order of states to "R, A" (and leave everything else the same) the error occurs in that instance as well. I believe the posters above have identified the issue at a level deeper than what I'm presenting, but I hope this is helpful

```

states:
A, R
end

jumps:
c, y, w, Pi, μ
end

shocks:
εₐ, εᵣ
end

parameters:
β      = .995
γ      = 1.0035
πst    = 1.005
τ      = 1.0
λₚ     = 0.1
λᵥ     = 0.1
ϕᵥ     = 1.0
ϕₚ      = 1.0
ρᵣ     = .8
ρₐ     = .2
σᵣ     = .001
σₐ     = .001
χ      = 1.0 
ν      = 0.11
end

solvers: Projection

equations:
R(+1) = σᵣ*εᵣ+ρᵣ*R+(1-ρᵣ)*log(γ*πst/β)
A(+1) = σₐ*εₐ+ρₐ*A+(1-ρₐ)*log(γ)
c = y*(1-(ϕₚ/2)*(Pi-πst)^2)-y*w*(ϕᵥ/2)*((Pi*exp(A)*w/w(-1))-πst*γ)^2
1.0 = (exp(R)/Pi(+1))*β*exp(-A(+1))*(c(+1)/c)^(-τ)
0.0 = (χ/λᵥ)*(1/w)*(c^τ)*(y^(1/ν)) +(1-(ϕᵥ/2)*((Pi*exp(A)*w/w(-1))-πst*γ)^2)*(1-(1/λᵥ)) - (Pi*exp(A)*w/w(-1))*ϕᵥ*((Pi*exp(A)*w/w(-1))-πst*γ) + ((Pi(+1)*exp(A(+1))*w(+1)/w)^2)*(y(+1)/y)*ϕᵥ*((Pi(+1)*exp(A(+1))*w(+1)/w)-πst*γ)/exp(R)
0.0 = (1-(ϕₚ/2)*(Pi-πst)^2 ) - Pi*ϕₚ*(Pi-πst) - (μ/λₚ) + β*Pi(+1)*ϕₚ*(Pi(+1)-πst)*(y(+1)/y)*(c(+1)/c)^(-τ)
w = (1-(ϕₚ/2)*(Pi-πst)^2)-μ
end

```
Steady state initial guess is 

```
x = [0.01349397258, 0.00349388925, 0.9, 0.97933426, 0.97933426, 0.9, 1.005, 0.1]
```
and I use `ChebyshevSchemeStoch` to solve

**Comment by RJDennis** [comment]
Paul,

out of interest, have you tried solving that model using a perturbation method?

Can you please tell me what domain you are using for the approximation scheme.

Thanks.

**Comment by RJDennis** [comment]
Roberto and Paul,

I have tagged a new release v0.5.8 that I think addresses the two bugs you raised.

Thanks.
